[package]
name = "crabapple"
version = "0.1.0"
authors = ["luxxxy <luxx4x@protonmail.com>", "kritanta"]
edition = "2018"
license = "Zlib"

[lib]
path = "lib.rs"

[dependencies]
objc = "0.2"
c_string = "0.7"
paste = "0.1"

[dev-dependencies]
rusty-hook = "^0.11.1"
